language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t bluebullet007/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bluebullet007/react-test npm test

after_success:
  - docker build -t bluebullet007/multi-client ./client
  - docker build -t bluebullet007/multi-nginx  ./nginx
  - docker build -t bluebullet007/multi-server ./server
  - docker build -t bluebullet007/multi-worker ./worker 

# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Take those images and push them to docker hub
  - docker push bluebullet007/multi-client
  - docker push bluebullet007/multi-nginx
  - docker push bluebullet007/multi-server
  - docker push bluebullet007/multi-worker     